version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.3.1
  php: {}
filters: &filters
  tags:
    only: /.*/
jobs:
  integration_install_php:
    docker:
      - image: cimg/base:edge
    steps:
      - php/install_php:
          extensions: "php7.4-bz2,php7.4-pgsql"
  integration_install_composer:
    executor: php/default
    steps:
      - php/install_composer
  integration_install_packages:
    executor: php/default
    steps:
      - checkout
      - php/install_packages:
          app_dir: "~/project/sample"
          cache_key: "composer.json"
workflows:
  test-deploy:
    jobs:
      - integration_install_php:
          filters: *filters
      - integration_install_composer:
          filters: *filters
      - integration_install_packages:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: circleci/php
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - integration_install_php
            - integration_install_composer
            - integration_install_packages
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
