description: Install Composer

parameters:
  install-flags:
    type: string
    default:  --install-dir=/usr/local/bin --filename=composer
    description: |
      By default, composer will be installed at "/usr/local/bin/composer", use this to override the standard install flags.

steps:
  - run:
      name: Install Composer
      command: |
        curl -sS https://getcomposer.org/installer -o composer-setup.php
        sudo php composer-setup.php <<parameters.install-flags>>
