description: Install Composer

parameters:
  install-dir:
    type: string
    default:  /usr/local/bin
    description: |
      By default, composer will be installed at "/usr/local/bin/composer", use this to override the install directory.
  install-version:
    type: string
    default: ''
    description: |
      By default, composer will install the latest composer version, use this to override the installed version.
  filename:
    type: string
    description: The filename parameter to pass to composer installation.
    default: 'composer'
steps:
  - run:
      name: Install Composer
      environment:
        ORB_EVAL_INSTALL_DIR: << parameters.install-dir >>
        ORB_VAL_INSTALL_VERSION: << parameters.install-version >>
        ORB_VAL_FILENAME: <<parameters.filename>>
      command: << include(scripts/install-composer.sh) >>
