description: "The official CircleCI PHP Docker image."
parameters:
  tag:
    description: "The `circleci/php` Docker image version tag."
    type: string
    default: "latest"
docker:
  - image: circleci/php:<< parameters.tag >>
