description: "The official CircleCI CIMG PHP Docker image."
parameters:
  tag:
    description: "The `cimg/php` Docker image version tag."
    type: string
docker:
  - image: cimg/php:<< parameters.tag >>
